// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtiU9JlFsayDQMkLPPUygGUJO-Nb8PcgQ',
    appId: '1:707322992902:web:b69cef021a7185463ba687',
    messagingSenderId: '707322992902',
    projectId: 'flutter-app-3481c',
    authDomain: 'flutter-app-3481c.firebaseapp.com',
    databaseURL: 'https://flutter-app-3481c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-3481c.appspot.com',
    measurementId: 'G-CKHJM4K8YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW50l6WizFbwHV9GQ3JyXiJTkfwH45N5M',
    appId: '1:707322992902:android:b0b452025c780cb83ba687',
    messagingSenderId: '707322992902',
    projectId: 'flutter-app-3481c',
    databaseURL: 'https://flutter-app-3481c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-3481c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhIXpz6VxRkuuXklhTSqLMhsbsEx5i-Dc',
    appId: '1:707322992902:ios:4798c34f28aa01a33ba687',
    messagingSenderId: '707322992902',
    projectId: 'flutter-app-3481c',
    databaseURL: 'https://flutter-app-3481c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-3481c.appspot.com',
    androidClientId: '707322992902-1smt2sganfqk49rsea9fa62nhs23t3kr.apps.googleusercontent.com',
    iosClientId: '707322992902-849sgh2a5v2rfea9eifndkme64lopodl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhIXpz6VxRkuuXklhTSqLMhsbsEx5i-Dc',
    appId: '1:707322992902:ios:4798c34f28aa01a33ba687',
    messagingSenderId: '707322992902',
    projectId: 'flutter-app-3481c',
    databaseURL: 'https://flutter-app-3481c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-3481c.appspot.com',
    androidClientId: '707322992902-1smt2sganfqk49rsea9fa62nhs23t3kr.apps.googleusercontent.com',
    iosClientId: '707322992902-849sgh2a5v2rfea9eifndkme64lopodl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app1',
  );
}
